version: '3'
services:
  nginx:
    volumes:
      - ./deploy/frontend/conf/nginx/cache-router.conf:/etc/nginx/conf.d/cache-router.conf
    links:
      - frontend
  frontend:
    image: registry.kube.indvp.com/scandipwa-oss/frontend:${PROJECT_TAG}
    build:
      context: frontend
      args:
        - BASEPATH=${BASEPATH}
        - NODEJS_VERSION=${NODEJS_VERSION}
    volumes:
      - ./src/localmodules/scandipwa-base-theme:/var/www/public
    working_dir: "/var/www/public"
    env_file: .env
    expose:
      - 3003
